-- require('user.plugins.airline')
require('user.plugins.diffview')
require('user.plugins.docker-dev')
require('user.plugins.devcontainercli')
require('user.plugins.fugitive')
require('user.plugins.fzf')
require('user.plugins.gitsigns')
require('user.plugins.harpoon')
require('user.plugins.lualine')
require('user.plugins.neogit')
-- require('user.plugins.netman') -- TODO: breaks when neovim is living inside docker container??
require('user.plugins.nvim-tree')
-- require('user.plugins.presence') -- not that usefull in the end?? :/
require('user.plugins.prettier')
-- require('user.plugins.undotree')
require('user.plugins.vimtex')
require('user.plugins.whichkey')
require('user.plugins.telescope')
