require('user.plugins.airline')
require('user.plugins.fugitive')
require('user.plugins.fzf')
require('user.plugins.harpoon')
require('user.plugins.nvim-tree')
require('user.plugins.prettier')
-- require('user.plugins.undotree')
require('user.plugins.vimtex')
require('user.plugins.whichkey')
require('user.plugins.telescope')
